
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: amigo_secreto_development


test:
  <<: *default
  database: amigo_secreto_test


production:
  <<: *default
  database: amigo_secreto_production
  # username: amigo_secreto
  # password: <%= ENV['AMIGO_SECRETO_DATABASE_PASSWORD'] %>
