# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a47b92c8c29a4fddf6fdfadbc999cc8721eb0e492d87e684cd5790e4e01e657957a2eea812df7b16939f76c9a37917b296dd4a7a1f3d72587e9621b3315ec8

test:
  secret_key_base: 8fcc3eec3420d0a6b8c0a3b9e8d00e9c1584a6f9049c06b2c8f019512ae9daf80056fce63594191dc4d27b3a460559dc087b2f8084de78e7077af533014aa816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
